name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
 
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: gcr.io/${{ github.actor }}/nodejs-docker:latest
        push: true
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
