name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.0.2
      with: 
        driver-opts: image=moby/buildkit:buildx-stable-1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: github-container-registry
        username: ${{ github.repository_owner  }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build image and push to GitHub COntainer Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: Dockerfile
        tags: gcr.io/${{ github.repository_owner  }}/nodejs-docker:latest
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
